const IMAGES = {
  Headshot: require("./Headshot.jpg").default,
  Projects: {
    Ciphr: {
      id: "Ciphr",
      name: "Ciphr",
      description: "A platform to share and solve coding algorithms.",
      image: require("./Portfolio/Ciphr.jpg").default,
      alt: "Ciphr Project",
      link: "https://ciphr.dev/",
      gitHub: "https://github.com/zachdrummond/ciphr",
      tech: ["React", "Node.js", "MongoDB", "Express"],
    },
    Gifted: {
      id: "Gifted",
      name: "Gifted",
      description: "Track all of your gifts in one organized place.",
      image: require("./Portfolio/Gifted.jpg").default,
      alt: "Gifted Project",
      link: "http://gifted-project2.herokuapp.com/",
      gitHub: "https://github.com/zachdrummond/gifted",
      tech: [],
    },
    GoogleBooksSearch: {
      id: "GoogleBooksSearch",
      name: "Google Books Search",
      description: "Find and save any book via Google Books API.",
      image: require("./Portfolio/GoogleBooksSearch.png").default,
      alt: "Google Books Search Project",
      link: "https://google-books-search-zd.herokuapp.com/search",
      gitHub: "https://github.com/zachdrummond/google-books-search",
      tech: [],
    },
    BudgetTracker: {
      id: "BudgetTracker",
      name: "Budget Tracker",
      description:
        "A progressive web app that helps you manage your financial budget.",
      image: require("./Portfolio/BudgetTracker.png").default,
      alt: "Budget Tracker Project",
      link: "https://pwa-budget-tracker-zd.herokuapp.com/",
      gitHub: "https://github.com/zachdrummond/pwa-budget-tracker",
      tech: [],
    },
    EatDaBurger: {
      id: "Eat-da-Burger",
      name: "Eat-da-Burger",
      description: "Create and eat a fictional burger.",
      image: require("./Portfolio/Eat-da-Burger.png").default,
      alt: "Eat-da-Burger Project",
      link: "https://eat-da-burger-zachdrummond.herokuapp.com/",
      gitHub: "https://github.com/zachdrummond/eat-da-burger",
      tech: [],
    },
    FindYourAdventure: {
      id: "FindYourAdventure",
      name: "Find Your Adventure",
      description: "Plan your next visit to a US National Park.",
      image: require("./Portfolio/FindYourAdventure.png").default,
      alt: "Find Your Adventure Project",
      link: "https://zachdrummond.github.io/Find-Your-Adventure/",
      gitHub: "https://github.com/zachdrummond/Find-Your-Adventure",
      tech: [],
    },
  },
  Skills: {
    Javascript: require("./Skills/Javascript.svg").default,
    React: require("./Skills/React.svg").default,
    Nodejs: require("./Skills/Nodejs.svg").default,
    Expressjs: require("./Skills/Expressjs.svg").default,
    HTML: require("./Skills/HTML.svg").default,
    CSS: require("./Skills/CSS.svg").default,
    Git: require("./Skills/Git.svg").default,
    MongoDB: require("./Skills/MongoDB.svg").default,
    MySQL: require("./Skills/MySQL.svg").default,
  },
};
export default IMAGES;
